// <auto-generated />
using System;
using HoaInfrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HoaInfrastructure.Migrations
{
    [DbContext(typeof(HoaDbContext))]
    [Migration("20190328200751_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HoaEntities.Entities.BoardMeeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("ScheduledLocation")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<DateTime>("ScheduledTime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BoardMeetings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e77551ba-78e2-4a36-8754-3ea5f12e1619"),
                            Created = new DateTime(2019, 3, 25, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(9066),
                            Description = "Test1",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 3, 29, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(9075),
                            Title = "Test1",
                            UserId = new Guid("5f76bd53-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("e77551ba-78e2-4a36-8754-3ea5f12e1618"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1215),
                            Description = "Test2",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 3, 30, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1230),
                            Title = "Test2",
                            UserId = new Guid("5f76bd54-b063-487a-89ca-c9ec6a9b6099")
                        },
                        new
                        {
                            Id = new Guid("1f12fe75-6216-47f8-a2a9-27218f338f19"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1271),
                            Description = "Test3",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 3, 31, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1275),
                            Title = "Test3",
                            UserId = new Guid("5f76bd54-b063-487a-89ca-c9ec6a9b6099")
                        },
                        new
                        {
                            Id = new Guid("dba13a97-b4b1-47ba-ada2-4fa4be2d116c"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1281),
                            Description = "Test4",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 1, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1284),
                            Title = "Test4",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("5e2ff88d-eef2-4b01-a513-c5ca2164cbb0"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1303),
                            Description = "Test5",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 2, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1308),
                            Title = "Test5",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("04c11869-1f6f-4caf-b50a-6bf76a965338"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1313),
                            Description = "Test6",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 3, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1317),
                            Title = "Test6",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("cdaebaa6-5f3d-4c5c-9610-ca83366545f0"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1322),
                            Description = "Test7",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1326),
                            Title = "Test7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("84ab11fc-7b9a-410a-a771-8ced9aa9ad15"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1332),
                            Description = "Test8",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1336),
                            Title = "Test8",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("5a57da2c-2e4d-44ce-82cf-b85c1dd7fbe1"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1343),
                            Description = "Test9",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1347),
                            Title = "Test9",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("c1e73294-9836-4339-8844-7c3ed02353ef"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1352),
                            Description = "Test10",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1356),
                            Title = "Test10",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("10e9997a-5cc9-493f-9fce-e7df9af4ce9d"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1362),
                            Description = "Test11",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1364),
                            Title = "Test11",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("4ab3d7b8-1538-47fd-92d0-124047893cc0"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1373),
                            Description = "Tesasfasft7",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1379),
                            Title = "asfasf",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("d081c247-754b-4b29-9a8b-4b6cd65c04b9"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1389),
                            Description = "Teasfasgst7",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1392),
                            Title = "afaf",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("eefc119d-d88d-40fe-af3c-7707f4d164cd"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1397),
                            Description = "Tesasgasgt7",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1400),
                            Title = "TsdhSFhest7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("87241e3f-fa47-4997-bfd1-42ab1f8b5d2d"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1406),
                            Description = "Test7asgasgasgasg",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1409),
                            Title = "Test7asgasg",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("3dc78c33-50fd-4ba9-be6a-65f5e9a98c4f"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1416),
                            Description = "TesFAHADFHDHt7",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1419),
                            Title = "TestsdghHR7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("f3a27a5f-2a01-49ca-b175-0c998e57cf49"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1424),
                            Description = "Te346364st7",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1426),
                            Title = "Tes4634636agasgt7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("467ca637-63a7-4c02-ada5-8c87ad42ee9d"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1431),
                            Description = "Tes2525235t7",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1434),
                            Title = "Test26236asg267",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("6c3f117e-0c35-4038-ad36-70d920d3e2fd"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1439),
                            Description = "Tes235235t7",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1442),
                            Title = "Te235asgasgdg235st7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("5603af66-cdb8-43d4-9cc5-5774944f34de"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1448),
                            Description = "Tes235235t7",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1451),
                            Title = "Tes23523asgdshgfh5t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("cc9be7f1-8c1b-464c-844d-daae7b61d1ca"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1459),
                            Description = "Test7235235",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1462),
                            Title = "Te235235st7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("765a78f4-84b7-43d2-9a82-bc4e87e4c56d"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1469),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1472),
                            Title = "Testsdghddgsdg2352357",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("ebd9b054-bb6b-479f-8d2a-9d3d4721fd3f"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1477),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1479),
                            Title = "Tes235sdgsdhsdh235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("e30b7790-78bd-4a31-9c6d-326b9fee0721"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1485),
                            Description = "Tes235235t7",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1488),
                            Title = "Tes23dgsdgsdggd5235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("4a12e195-c5c0-4f71-a81e-6016b510baab"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1495),
                            Description = "Tes25235t7",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1498),
                            Title = "Tes25sdgsdgsdg235235235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("aaefd224-03fb-4c04-b70e-6028c50e145e"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1502),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1505),
                            Title = "Tes2352sdgsdg35235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("a993c2a8-a2bc-4333-a130-577f8647b039"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1510),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1513),
                            Title = "Tes235sdg235235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("a90ca1a6-11e5-412f-b2d6-e3b951d4b7e0"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1518),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1522),
                            Title = "Tes235235235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("cb126c20-1f81-41bf-965d-81c046d0a6ee"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1529),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1533),
                            Title = "Tes235235235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("5a5f5108-ec4a-487b-bfb2-3520bc518979"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1539),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1542),
                            Title = "Tes235235235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("75eaa8c2-ab30-4396-b31c-ef258bffde51"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1549),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1552),
                            Title = "Tes235235235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("7c158e13-81b0-4ec8-ab91-774dffcf4695"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1558),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1561),
                            Title = "Tes235235235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("3b6891c0-5391-433d-a47e-6040c8b96645"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1566),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1569),
                            Title = "Tes235235235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("7a550a23-e95c-4bdb-9be7-653c2b8f2d0a"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1573),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1577),
                            Title = "Tes235235235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("c5d8664c-3705-4d58-ae63-a4200306ac89"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1605),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1609),
                            Title = "Tes235235235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("74f3ff3c-5623-4a86-b2f1-eb448ccbc565"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1614),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1617),
                            Title = "Tes235235235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("af1b438d-714b-4aef-8cbf-a41e81fc844f"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1624),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1628),
                            Title = "Tes235235235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("7d437767-98d5-4c0e-8b56-2215e9ecc010"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1633),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1636),
                            Title = "Tes235235235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("2a13c6bb-8a4e-4746-ad7e-3476c98a17f1"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1776),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1783),
                            Title = "Tes235235235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("69faef0d-a88a-4d70-93cd-e65ce180ad82"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1787),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1793),
                            Title = "Tes235235235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("e0a56604-60cb-4a5b-8e45-8f2cf10c4a98"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1801),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1806),
                            Title = "Tes235235235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("fd4445e2-954b-42bc-9aaf-8d4cac99a82e"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1813),
                            Description = "Test2352357",
                            ScheduledLocation = "a",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 482, DateTimeKind.Local).AddTicks(1816),
                            Title = "Tes235235gasgasg235t7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        });
                });

            modelBuilder.Entity("HoaEntities.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<Guid?>("ParentCommentId");

                    b.Property<Guid>("PostId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e77551ba-78e3-4a36-9754-4ea5f12e1619"),
                            Created = new DateTime(2019, 3, 23, 13, 7, 50, 480, DateTimeKind.Local).AddTicks(9987),
                            Message = "Test1",
                            PostId = new Guid("e77551ba-78e3-4a36-8754-3ea5f12e1619"),
                            UserId = new Guid("5f76bd53-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("e77551ba-78e4-4a36-7754-5ea5f12e1618"),
                            Created = new DateTime(2019, 3, 26, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(2001),
                            Message = "Test2",
                            ParentCommentId = new Guid("e77551ba-78e3-4a36-9754-4ea5f12e1619"),
                            PostId = new Guid("e77551ba-78e3-4a36-8754-3ea5f12e1619"),
                            UserId = new Guid("5f76bd53-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("6264505f-fd9b-469e-908e-25847f9186c2"),
                            Created = new DateTime(2019, 3, 25, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(3755),
                            Message = "Test3",
                            ParentCommentId = new Guid("e77551ba-78e3-4a36-9754-4ea5f12e1619"),
                            PostId = new Guid("e77551ba-78e3-4a36-8754-3ea5f12e1619"),
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("c604b1c2-4d5d-4d05-bca1-0ad5f52f0a50"),
                            Created = new DateTime(2019, 3, 27, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(3790),
                            Message = "Test4",
                            ParentCommentId = new Guid("e77551ba-78e4-4a36-7754-5ea5f12e1618"),
                            PostId = new Guid("e77551ba-78e3-4a36-8754-3ea5f12e1619"),
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("e09a1cb7-6708-432d-9cda-5cf97e703c70"),
                            Created = new DateTime(2019, 3, 27, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(3795),
                            Message = "Test5",
                            PostId = new Guid("e77551ba-78e3-4a36-8754-3ea5f12e1619"),
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("e37f45b1-8e1a-4bcd-95b5-a5a200cefa67"),
                            Created = new DateTime(2019, 3, 27, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(3808),
                            Message = "Test6",
                            PostId = new Guid("e77551ba-78e3-4a36-8754-3ea5f12e1619"),
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("abb525ca-0536-43e4-bda9-fccb48f4f27c"),
                            Created = new DateTime(2019, 3, 26, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(3826),
                            Message = "Test7",
                            PostId = new Guid("e77551ba-78e4-4a36-8754-3ea5f12e1618"),
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        });
                });

            modelBuilder.Entity("HoaEntities.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("ImageName");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<DateTime>("ScheduledTime");

                    b.Property<string>("ThumbnailName");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e77551ba-78e2-4a36-8754-3ea5f12e1619"),
                            Created = new DateTime(2019, 3, 25, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(4244),
                            ImageName = "Event_Original_01-30-2019_11-41-16.jpg",
                            Message = "Test1Test1Test1Te st1Tes t1Test1T est1Test 1Test1T st1Test1Te st1Test1Tes t1Test1Test1Test 1Test1Test1Test1Test1Test1Test1T est1Test1Test1Test1Test1Test 1Test1Te st1T est1Test1Test1Test1Te st1Test1Tes t1Test1Test1Te st1Test1Test1Test1Test1Test1Test 1Test1Test1Test 1Test1Test1Te t1Test1Test1Test1 Test1Test1Te st1Tes t1Test 1Test1Test1 Test1Test1 Test1Test1Test1Test1Test1Te st1Test1Te st1Test1Test1 Test1Test1Test1T est1Test1Test1Test1Test1Test1Test1Test1Test1Test1Test 1Test1Te st1Test1Test1Te st1Test1 Test1Test1Test1Test 1Test1Te st1Test1Test1Te st1Test1 Test1Test1Test1Test 1Test1Te st1Test1Test1Te st1Test1Test1Test1Test1Test 1Test1Te st1Test1Test1Te st1Test1 Test1Test1Test1Test 1Test1Te st1Test1Test1Te st1Test1 Test1Test1Test1Test 1Test1Te st1Test1Test1Te st1Test1Test1Test1Test1Test 1Test1Te st1Test1Test1Te st1Test1 Test1Test1Test1Test 1Test1Te st1Test1Test1Te st1Test1 Test1Test1Test1Test 1Test1Te st1Test1Test1Te st1Test1 Test1Test1Test1Test 1Test1Te st1Test1Test1Te st1Test1",
                            ScheduledTime = new DateTime(2019, 3, 29, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(4254),
                            ThumbnailName = "Event_Thumbnail_01-30-2019_11-41-16.jpg",
                            Title = "Test1",
                            UserId = new Guid("5f76bd53-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("e77551ba-78e2-4a36-8754-3ea5f12e1618"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(6373),
                            ImageName = "Event_Original_01-30-2019_11-41-16.jpg",
                            Message = "Test2",
                            ScheduledTime = new DateTime(2019, 3, 30, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(6388),
                            ThumbnailName = "Event_Thumbnail_01-30-2019_11-41-16.jpg",
                            Title = "Test2",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("19cd0feb-ca87-4d84-ad1d-9f63656439b2"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(6425),
                            ImageName = "Event_Original_01-30-2019_11-41-16.jpg",
                            Message = "Test3",
                            ScheduledTime = new DateTime(2019, 3, 31, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(6429),
                            ThumbnailName = "Event_Thumbnail_01-30-2019_11-41-16.jpg",
                            Title = "Test3",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("a435b497-502c-4c58-a345-14d32229be4e"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(6439),
                            ImageName = "Event_Original_01-30-2019_11-41-16.jpg",
                            Message = "Test4",
                            ScheduledTime = new DateTime(2019, 4, 1, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(6442),
                            ThumbnailName = "Event_Thumbnail_01-30-2019_11-41-16.jpg",
                            Title = "Test4",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("330609f8-13d3-40b6-b78a-221538d8dda0"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(6449),
                            ImageName = "Event_Original_01-30-2019_11-41-16.jpg",
                            Message = "Test5",
                            ScheduledTime = new DateTime(2019, 4, 2, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(6452),
                            ThumbnailName = "Event_Thumbnail_01-30-2019_11-41-16.jpg",
                            Title = "Test5",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("9f78ec31-c59a-4345-90ec-7e6736611d95"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(6458),
                            ImageName = "Event_Original_01-30-2019_11-41-16.jpg",
                            Message = "Test6",
                            ScheduledTime = new DateTime(2019, 4, 3, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(6461),
                            ThumbnailName = "Event_Thumbnail_01-30-2019_11-41-16.jpg",
                            Title = "Test6",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("40f93431-07ea-4c22-b0ff-047100ee95bc"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(6468),
                            ImageName = "Event_Original_01-30-2019_11-41-16.jpg",
                            Message = "Test7",
                            ScheduledTime = new DateTime(2019, 4, 4, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(6471),
                            ThumbnailName = "Event_Thumbnail_01-30-2019_11-41-16.jpg",
                            Title = "Test7",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        });
                });

            modelBuilder.Entity("HoaEntities.Entities.MeetingMinute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BoardMeetingId");

                    b.Property<DateTime>("Created");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BoardMeetingId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("MeetingMinutes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e77551ba-78e3-4a36-9754-3ea5f12e1619"),
                            BoardMeetingId = new Guid("e77551ba-78e2-4a36-8754-3ea5f12e1619"),
                            Created = new DateTime(2019, 3, 25, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(6807),
                            FileName = "test1.txt",
                            UserId = new Guid("5f76bd53-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("e77551ba-78e4-4a36-7754-3ea5f12e1618"),
                            BoardMeetingId = new Guid("e77551ba-78e2-4a36-8754-3ea5f12e1618"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 481, DateTimeKind.Local).AddTicks(8775),
                            FileName = "test2.txt",
                            UserId = new Guid("5f76bd53-b065-487a-89ca-c9ec6a9b60c9")
                        });
                });

            modelBuilder.Entity("HoaEntities.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<bool>("Important");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e77551ba-78e3-4a36-8754-3ea5f12e1619"),
                            Created = new DateTime(2019, 3, 25, 13, 7, 50, 480, DateTimeKind.Local).AddTicks(6692),
                            Important = true,
                            Message = "Test1",
                            Title = "Test1",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("e77551ba-78e4-4a36-8754-3ea5f12e1618"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 480, DateTimeKind.Local).AddTicks(9320),
                            Important = false,
                            Message = "Test2",
                            Title = "Test2",
                            UserId = new Guid("5f76bd53-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("13301ce4-0913-4681-8506-a19a99286047"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 480, DateTimeKind.Local).AddTicks(9619),
                            Important = false,
                            Message = "Test3",
                            Title = "Test3",
                            UserId = new Guid("5f76bd53-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("0bd70845-1647-4d62-b1b2-f64626968727"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 480, DateTimeKind.Local).AddTicks(9629),
                            Important = true,
                            Message = "Test4",
                            Title = "Test4",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        },
                        new
                        {
                            Id = new Guid("20e5e28c-35b4-42f1-a366-3efaf30e96f1"),
                            Created = new DateTime(2019, 3, 28, 13, 7, 50, 480, DateTimeKind.Local).AddTicks(9633),
                            Important = true,
                            Message = "Test5",
                            Title = "Test5",
                            UserId = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9")
                        });
                });

            modelBuilder.Entity("HoaEntities.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<DateTime?>("Joined")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<bool>("Reminder");

                    b.Property<string>("SocialId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f76bd52-b065-487a-89ca-c9ec6a9b60c9"),
                            Active = true,
                            Email = "abc@123.com",
                            FirstName = "VN",
                            Joined = new DateTime(2019, 3, 28, 13, 7, 50, 467, DateTimeKind.Local).AddTicks(7818),
                            LastName = "R",
                            Reminder = false,
                            SocialId = "12345"
                        },
                        new
                        {
                            Id = new Guid("5f76bd53-b065-487a-89ca-c9ec6a9b60c9"),
                            Active = true,
                            Email = "xyz@123.com",
                            FirstName = "Meera",
                            Joined = new DateTime(2019, 3, 28, 13, 7, 50, 480, DateTimeKind.Local).AddTicks(6237),
                            LastName = "Lao",
                            Reminder = false,
                            SocialId = "123"
                        },
                        new
                        {
                            Id = new Guid("5f76bd54-b063-487a-89ca-c9ec6a9b6099"),
                            Active = true,
                            Email = "ctt@123.com",
                            FirstName = "A",
                            Joined = new DateTime(2019, 3, 28, 13, 7, 50, 480, DateTimeKind.Local).AddTicks(6515),
                            LastName = "B",
                            Reminder = true,
                            SocialId = "1234567"
                        });
                });

            modelBuilder.Entity("HoaEntities.Entities.BoardMeeting", b =>
                {
                    b.HasOne("HoaEntities.Entities.User", "CreatedBy")
                        .WithMany("BoardMeetings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HoaEntities.Entities.Comment", b =>
                {
                    b.HasOne("HoaEntities.Entities.Post", "CommentForPost")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HoaEntities.Entities.User", "CreatedBy")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HoaEntities.Entities.Event", b =>
                {
                    b.HasOne("HoaEntities.Entities.User", "CreatedBy")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HoaEntities.Entities.MeetingMinute", b =>
                {
                    b.HasOne("HoaEntities.Entities.BoardMeeting", "Meeting")
                        .WithOne("MeetingNotes")
                        .HasForeignKey("HoaEntities.Entities.MeetingMinute", "BoardMeetingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HoaEntities.Entities.User", "CreatedBy")
                        .WithMany("MeetingMinutes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HoaEntities.Entities.Post", b =>
                {
                    b.HasOne("HoaEntities.Entities.User", "CreatedBy")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
